### ISSUE TITLE
Templates should include a way to query Attendease metadata.

### ISSUE THREAD

**Issue by aparticulate** [attendease/jekyll-attendease#78]
Attendease admin allows to create metadata for Sponsor, Presenter instances
Such as,

![attendease_schedule_builder](https://cloud.githubusercontent.com/assets/1588227/14258798/ec9bfd94-fa58-11e5-8e67-3a7906f5fc62.png)

For our project, we are looking to use metadata to create arbitrary pages based on Attendease Presenter, Sponsor metadata. 

For instance,
/presenters#demos
/presenters#rising-stars
/presenters#speakers

These pages would return a list of presenters based on the client-submitted metadata.
When building a theme on the Attendease default and I don't have a way of seeing this information.

Can jekyll-attendease provide this?

Suggested output, using a data-attribute: (For a presenter)
_e.g._
```
<div class="attendease-presenter" data-presenter-id="{{ presenter.id }}" data-presenter-meta="{{ presenter.metadata }}">
</div>
```

Current presenters/index.html
```
<div class="attendease-presenter{% if presenter.featured %} attendease-featured-presenter{% endif %}" data-presenter-id="{{ presenter.id }}">
```
presenters: https://github.com/attendease/jekyll-attendease/blob/master/templates/attendease/presenters/index.html#L11
presenter instance: https://github.com/attendease/jekyll-attendease/blob/master/templates/attendease/presenters/presenter.html

---
Via: 
https://github.com/coverall/Attendease-Third-Party-Themes/issues/1132
https://github.com/coverall/Attendease-Third-Party-Themes/issues/1131
https://github.com/coverall/Attendease-Third-Party-Themes/issues/1133

**Comment by pgib** [comment]
@aparticulate The plugin is already pulling in any metadata that exists. Is there any event you're using that has some so we can verify how to access it?

**Comment by aparticulate** [comment]
@pgib Oh really?

Here's the event I'm working on:
https://dashboard.attendease.com/events/fflondon16/details

The theme:
https://fflondon16.attendease.com/presenters/

I'm going to add a query string for three predetermined metadata key/values:
```
Key  | Value 
page | demos  https://fflondon16.attendease.com/presenters#demos
page | rising-stars  https://fflondon16.attendease.com/presenters#rising-stars
page | partners https://fflondon16.attendease.com/presenters#partners
```

What would be the best way to access this metadata (if available)?

**Comment by pgib** [comment]
I would expect that `{{ presenter.meta.page }}` would have the data you're looking for.

**Comment by aparticulate** [comment]
@pgib: Ah, okay. Part of our internal requirements are to avoid making a theme for this project. (Simply building on top of default theme).

Shall I make a PR to include this on the template for Presenters only?
